name: yambot
channels:
  - conda-forge
dependencies:
  - python=3.9
  - jupyterlab
  - pygame
  - numpy
  - gymnasium[classic_control]
  - sb3-contrib
  - pip
  - pip:
    - mlflow-skinny
    - azureml-mlflow
    - tensorflow
    - ipykernel
    - black